## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to override the default test script
script:
 - julia -e 'ENV["JULIA_NUM_THREADS"]=4; using Pkg; Pkg.clone(pwd()); Pkg.build("NNPACK"); Pkg.test("NNPACK"; coverage=true)'
